import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import{createRequire}from'node:module';import{boot,frames,memory,symbols,GameBoyMode,PadKey}from'../../../../editor/tests/emulator.mjs';
const root=process.cwd(),dir=path.resolve('projects/touhou-kouma/touhou-kouma-design/pv-v22'),l=createRequire(import.meta.url)('../../../../editor/build/library.cjs'),romPath=path.resolve('projects/touhou-kouma/build/Release/touhou-kouma-v22.gb'),rom=fs.readFileSync(romPath),sha=crypto.createHash('sha256').update(rom).digest('hex'),workflow=JSON.parse(fs.readFileSync('projects/touhou-kouma/workflow.json'));if(workflow.approval?.romSha256!==sha)throw Error('approval');const syms=symbols(romPath.replace(/\.gb$/,'.map')),g=l.readGame(root,'touhou-kouma'),hz=4194304/70224;
for(const name of process.argv.slice(2).length?process.argv.slice(2):['reimu','marisa','remilia','flandre']){
const bossRun=['remilia','flandre'].includes(name),character=name==='reimu'?0:1,stage=name==='remilia'?5:name==='flandre'?6:0,out=dir+'/captures/'+name;fs.mkdirSync(out,{recursive:true});const gb=boot(rom,GameBoyMode.Cgb),events=[],marks=[],v=fs.openSync(out+'/frames.rgb','w'),a=fs.openSync(out+'/audio.s16le','w');let elapsed=0,recorded=0,held=[],record=!bossRun,firstRecorded=null,scenePrevious=-1,phasePrevious=-1,peakBullets=0,peakOam=0,rate=gb.audio_sampling_rate(),channels=gb.audio_channels();
const snap=()=>{const m=memory(gb),r=m.ram,b=n=>r[syms[n]-0xc000],w=n=>r.readUInt16LE(syms[n]-0xc000),base=syms._ce_state-0xc000;let boss;for(let i=0;i<39;i++){const p=syms._ce_entities-0xc000+i*25;if(r[p]===2)boss={id:g.bosses[r[p+1]].id,hp:r[p+3],phase:r[p+4],x:r.readInt16LE(p+12)/16,y:r.readInt16LE(p+14)/16};}return{ready:r[syms._ce_trace-0xc000]===67&&r[syms._ce_trace-0xc000+1]===69,scene:b('_ce_scene'),tick:w('_ce_state'),x:r.readInt16LE(base+14)/16,y:r.readInt16LE(base+16)/16,lives:r[base+19],pause:b('_ce_pause'),battle:b('_ce_battle_mode'),bullets:b('_ce_bg_count'),bomb:b('_ce_bomb_left'),bombs:b('_ce_bombs'),latch:b('_ce_bomb_latch'),respawn:w('_ce_respawn'),locked:b('_ce_boss_invulnerable'),boss,oam:[...m.oam].filter((v,i)=>i%4===0&&v>8&&v<160).length};};
function step(keys=[]){if(keys.join()!=held.join()){for(const k of held)gb.key_lift(PadKey[k]);for(const k of keys)gb.key_press(PadKey[k]);held=[...keys];events.push({frame:elapsed,keys});}l.clockRomFrame(gb);const pcm=gb.audio_buffer_eager(true),s=snap();if(bossRun&&!record&&(s.scene===5||s.boss)){record=true;firstRecorded=elapsed;}
if(record){firstRecorded??=elapsed;fs.writeSync(v,gb.frame_buffer_eager());const b=Buffer.alloc(pcm.length*2);for(let i=0;i<pcm.length;i++)b.writeInt16LE(Math.max(-32768,Math.min(32767,pcm[i]*512)),i*2);fs.writeSync(a,b);recorded++;peakBullets=Math.max(peakBullets,s.bullets);peakOam=Math.max(peakOam,s.oam);if(s.scene!==scenePrevious||s.boss?.phase!==phasePrevious||s.bomb&&!(marks.at(-1)?.kind==='bomb')){const kind=s.bomb?'bomb':'state';marks.push({frame:recorded-1,seconds:(recorded-1)/hz,kind,...s});scenePrevious=s.scene;phasePrevious=s.boss?.phase;}}
elapsed++;return s;}
const wait=(fn,max=3000,keys=[])=>{let s;for(let i=0;i<max;i++){s=step(keys);if(fn(s))return s;}throw Error(name+' wait '+JSON.stringify(s));},hold=(keys,n)=>{let s;for(let i=0;i<n;i++)s=step(keys);return s;},tap=k=>{hold([k],4);hold([],12);};
try{wait(s=>s.scene===0&&s.ready,3000);hold([],bossRun?20:150);if(stage){tap('Down');for(let i=0;i<stage;i++)tap('Right');}tap('A');wait(s=>s.scene===10);if(name==='reimu'){hold([],90);tap('Right');hold([],100);tap('Left');hold([],70);}else{tap('Right');hold([],bossRun?10:80);}tap('A');wait(s=>s.scene===1);hold([],30);let s=snap(),bombFired=false,bombPress=0,bossAge=0,battleStart=-1,lastTick=s.tick;let cutins=0,previousScene=s.scene;
for(let i=0;i<(bossRun?24000:4500);i++){let keys=[];if(s.pause){tap('Start');s=snap();continue;}if(s.scene===5||s.scene===9){if(i%24<6)keys=['A'];}else if(s.scene===1){if(!bossRun){keys=['A'];if(s.tick%300<45)keys.push('Left');else if(s.tick%300>=150&&s.tick%300<195)keys.push('Right');if(s.tick>=500&&!bombFired&&!s.respawn&&s.bombs){bombPress=8;bombFired=true;}if(s.tick>=450&&s.tick<490)keys=[];if(bombPress>0){keys=['A','B'];bombPress--;}if(s.tick>=1100)break;}else if(!s.boss){keys=['A'];if(s.x>8)keys.push('Left');if(s.y>16)keys.push('Up');}else{if(s.tick!==lastTick)bossAge++;if(s.y<112)keys.push('Down');if(s.x<75)keys.push('Right');else if(s.x>85)keys.push('Left');if(!s.locked&&s.battle===2){battleStart=battleStart<0?s.tick:battleStart;if(s.tick-battleStart>150)keys.push('A');if(s.boss.phase>=3&&s.tick-battleStart>1400)break;}}}if(s.scene===7&&previousScene!==7)cutins++;previousScene=s.scene;if(bossRun&&recorded>4800)break;s=step(keys);lastTick=s.tick;if(s.scene===14||s.scene===13||s.scene===4){marks.push({frame:recorded,kind:'gameover',...s});break;}}
hold([],60);fs.writeFileSync(out+'/capture.json',JSON.stringify({name,romPath,romSha256:sha,mode:'CGB',displayHz:hz,displayFrames:recorded,sourceDisplayFrames:elapsed,firstRecorded,rate,channels,peakBullets,peakOam,marks,events,note:'Approved production ROM. Ordinary controller inputs only, no ROM/RAM patches. One hardware display interval per captured frame; native slowdown preserved.'},null,2));console.log(name,{recorded,seconds:recorded/hz,peakBullets,marks:marks.length});}finally{fs.closeSync(v);fs.closeSync(a);gb.free();}}
