const fs = require('node:fs');
const path = require('node:path');
const base=__dirname;
for(const d of ['prompts','references','backgrounds','storyboards','provenance'])fs.mkdirSync(path.join(base,d),{recursive:true});
const modelFiles=['characters-01-heroes.png','characters-02-rumia-cirno.png','characters-03-meiling-clean.png','characters-04-patchouli-sakuya.png','characters-05-scarlet-sisters-corrected.png'];
for(const f of modelFiles)fs.copyFileSync(path.join(base,'../op-movie-v1/references',f),path.join(base,'references',f));
const cast={
  1:{name:'Reimu Hakurei',ja:'博麗霊夢',en:'long chestnut hair, brown eyes, large red-white bow, red calf-length shrine dress, yellow necktie and detached white sleeves',jp:'長い栗色の髪、茶色の瞳、大きな赤白リボン、ふくらはぎ丈の赤い巫女服、黄色の胸元の結び、白い分離袖'},
  2:{name:'Marisa Kirisame',ja:'霧雨魔理沙',en:'blonde hair with a side braid, amber eyes, black witch hat with white bow, black calf-length dress and white apron, brown broom and octagonal focus',jp:'金髪と片側の編み込み、琥珀色の瞳、白リボン付き黒い魔女帽、ふくらはぎ丈の黒い服と白エプロン、茶色の箒、八角形の魔法の道具'},
  3:{name:'Rumia',ja:'ルーミア',en:'blonde bob, red eyes, small red side ribbon, black dress over a white shirt with red tie',jp:'金髪ボブ、赤い瞳、小さな赤い横リボン、白シャツと赤ネクタイ、黒いワンピース'},
  4:{name:'Cirno',ja:'チルノ',en:'ice-blue bob, blue hair bow and dress, red neck ribbon, white zigzag hem and six rigid ice-wing shards',jp:'水色ボブ、青い髪リボンと服、赤い胸リボン、白い山形の裾、左右3本ずつの氷の翼'},
  5:{name:'Hong Meiling',ja:'紅美鈴',en:'long red hair with twin braids, green star beret, gold-trimmed green tunic, loose white trousers and green wrist guards',jp:'長い赤髪と二本の編み込み、星付き緑帽、金縁の緑の長衣、ゆったりした白ズボン、緑の手甲'},
  6:{name:'Patchouli Knowledge',ja:'パチュリー・ノーレッジ',en:'long purple hair, crescent pink cap, red and blue ribbons, pink-lavender striped gown and purple book',jp:'長い紫髪、三日月飾りの桃色帽、赤青のリボン、桃色と薄紫の縦縞の長衣、紫の本'},
  7:{name:'Sakuya Izayoi',ja:'十六夜咲夜',en:'silver bob with small braids, blue eyes, white maid headband, navy maid dress, white apron and green neck bow',jp:'銀髪ボブと小さな編み込み、青い瞳、白いメイドの髪飾り、紺の服、白いエプロン、緑の胸リボン'},
  8:{name:'Remilia Scarlet',ja:'レミリア・スカーレット',en:'short light-blue hair, red eyes, pink frilled cap and dress with long bell sleeves, crimson bows and one pair of purple membrane bat wings',jp:'短い水色髪、赤い瞳、淡桃色のフリル帽と長いベル袖の服、紅いリボン、一対の紫の膜状のコウモリ翼'},
  9:{name:'Flandre Scarlet',ja:'フランドール・スカーレット',en:'blonde side ponytail, red eyes, white cap with red bow, red dress and yellow necktie, dark wing spars with hanging rainbow crystals',jp:'金髪の横ポニーテール、赤い瞳、赤リボン付き白帽、赤い服と黄色の胸元の結び、虹色の結晶を下げた暗色の翼の枝'}
};
const clips=[
{id:'clip-01',title:'ふたりに会いに、青空へ',cast:[1,2],sources:{1:[1,'top','上段'],2:[1,'bottom','下段']},times:[0,1.5,3,5,6.5,8],labels:['霊夢の振り向き','魔理沙がレンズ前へ','背中合わせの二人','霊夢の高速すれ違い','魔理沙の急な切り返し','縁側のかわいいひと呼吸'],pacing:'笑顔と目線で登場。中盤の3秒だけ、強い遠近感の高速カットへ。最後は縁側の小さな仕草で和らげる。',
uploads:['references/'+modelFiles[0],'backgrounds/background-01-shrine.png','backgrounds/background-03-sky.png','storyboards/storyboard-01.png'],board:4,
environments:[{id:10,pic:2,en:'the sunlit shrine courtyard: red torii, cherry blossoms, wooden veranda and mint-green foliage',ja:'日向の神社。赤い鳥居、桜、木の縁側、明るい緑の木々'},{id:11,pic:3,en:'the open cyan sky with large white clouds and a distant tiny manor',ja:'大きな白い雲と、はるか下の小さな館がある水色の空'}],
summaryEN:'Introduce <Subject 1> and <Subject 2> through charming looks, one lively duo pose, two spectacular flight inserts in <Subject 11>, and a playful veranda beat in <Subject 10>. This is a character-led visual-novel opening montage. <Picture 4> supplies composition; the shots jump associatively between moods. Warm smiles are the main attraction, with three seconds of bold aerial camera movement.',
summaryJA:'<Subject 1> と <Subject 2> のかわいい表情、二人のポーズ、<Subject 11> での鮮烈な飛行カット、<Subject 10> の縁側の小さな仕草をつなぐ。キャラクターの魅力が主役のギャルゲーム風OP。<Picture 4> の構図を使い、連想的な編集で場所と気分を切り替える。笑顔を軸に、中盤の3秒だけ空中カメラを大胆に動かす。',
shotsEN:[
'A close three-quarter view of <Subject 1> fills the frame as her white sleeve finishes sweeping past the lens. In <Subject 10>, she turns toward us, her large red bow catching warm sunlight, and her composed face opens into a small inviting smile. Push forward a few centimeters at eye level. Cherry petals drift through the soft background; a crisp cloth swish and one light sandal tap accent her turn.',
'Cut to <Subject 2> approaching head-first beside the shrine. The bare wooden handle leads toward the lens; the straw bundle trails behind her hips. Her anatomical right hand grips the shaft, thumb opposing four curled fingers; her left hand touches the hat brim as she winks. Both wrists connect naturally to their respective forearms. Track backward at face height; braid and white bow stream behind. The handle passes beneath the lens as the courtyard slides sideways in parallax. Broom wind ends with a hat-fabric rustle.',
'Cut to a waist-up duo composition: <Subject 1> and <Subject 2> stand back-to-back, then glance toward the camera from opposite shoulders. Their red and black silhouettes form a balanced center against softly defocused cherry blossom and sky. A brisk quarter-orbit settles into their shared smile. Each holds one recognizable prop low, leaving both faces clear. A petal brushes Marisa’s hat with a tiny dry tick.',
'Cut directly into <Subject 11>: <Subject 1> sweeps diagonally past the lens, sleeve and talisman sharply foreshortened in the foreground, body receding behind. The camera whips around her shoulder as she banks around one cloud edge. Her focused eyes stay visible for an instant before she clears frame. Use a fast near-to-far change of scale and a clean air crack to convey force, keeping the action readable.',
'Reverse screen direction on the cut to <Subject 2> in low frontal flight. Her anatomical right hand keeps its shaft grip; her left holds the octagonal focus. The bare handle leads beneath the camera, straw trailing behind her hips on the same straight shaft. She banks against a huge cloud. Her single black skirt flares over opaque white drawers with separate knee-length legs and gathered cuffs. Snap-track her face, then follow her into the distance. One golden glint leaves the focus. Broom wind rises and cuts sharply.',
'Cut to the two sitting side by side on the shrine veranda, returning immediately to warm daylight and everyday charm. <Subject 2> straightens her slightly crooked hat; <Subject 1> notices and hides a small smile behind a folded sleeve. Drift gently sideways at seated eye level, keeping their faces large. Cloth, wood and leaves replace the flight roar. End on their exchanged glance at 00:10.000.'
],
shotsJA:[
'<Subject 1> の白い袖がレンズ前を抜け、斜め前からの顔の寄りが現れる。<Subject 10> の日向でこちらへ振り向き、大きな赤リボンに光を受け、落ち着いた顔から小さな親しみのある笑みに変わる。目の高さで数センチだけ寄る。ぼけた背景に桜の花びら。袖の音と軽い下駄の音を振り向きに合わせる。',
'神社の横を頭からこちらへ近づく <Subject 2> へ切る。木の柄の先端がレンズへ向かい、穂は腰の後ろへ続く。本人の右手で柄を握り、親指と巻き付けた4本の指を向かい合わせる。左手で帽子のつばに触れてウインク。両手首はそれぞれの前腕へ自然につながる。顔の高さで後退し、編み込みと白リボンをなびかせる。柄の先端がレンズの下を通り、境内が横へ視差で流れる。箒の風の末尾に帽子の布の音。',
'背中合わせの <Subject 1> と <Subject 2> を腰上で捉える。二人が反対側の肩越しにこちらを見る。ぼけた桜と空を背に、赤と黒の輪郭を中央で釣り合わせる。カメラは素早く四分の一周して、二人の笑顔で止まる。小道具は顔より下で構える。花びらが魔理沙の帽子に触れる小さな音。',
'<Subject 11> へ直接切り替え、<Subject 1> が斜めにレンズをかすめる。手前の袖と札を強い遠近感で大きく、体を奥へ小さく見せる。雲の縁でバンクする肩の周囲へカメラを素早く振る。一瞬だけ鋭い瞳を捉えて画面外へ抜く。手前から奥への大きなサイズ変化と、鋭い風の音で勢いを出し、動きは読めるようにする。',
'カットで画面上の進行方向を反転し、低い正面から飛ぶ <Subject 2>。本人の右手は柄を握り続け、左手で八角形の道具を持つ。木の柄の先端からカメラの下へ進み、同じ一本の真っ直ぐな柄の後端にある穂が腰の後ろへ続く。巨大な雲を背にバンク。一枚の黒いスカートが広がり、不透明な白いドロワーズが見える。左右の脚に分かれた膝丈で、裾を絞った形。顔へ急追従して奥へ飛び去る動きを追う。道具が金色に一度光り、箒の風が高まって鋭く切れる。',
'神社の縁側に並んで座る二人へ切り、日常の暖かな光へ戻す。<Subject 2> が少し曲がった帽子を直し、<Subject 1> は気づいて袖の陰に小さな笑みを隠す。座った目の高さから穏やかに横移動し、顔を大きく保つ。飛行音を布・木・葉の音へ切り替える。二人の目線の交換で00:10.000に終了。'
]},
{id:'clip-02',title:'好きになる、小さな仕草',cast:[7,6,5,3,4],sources:{3:[1,'top','上段'],4:[1,'bottom','下段'],5:[2,'single character','唯一の人物'],6:[3,'top','上段'],7:[3,'bottom','下段']},times:[0,1.5,3,4.5,6,8],labels:['咲夜のティーサービス','本から覗くパチュリー','美鈴の照れた敬礼','ルーミアとおやつ','チルノの氷の花','五人のお茶会'],pacing:'視線・手元・表情で5人を紹介。トレイの円、本の縁、帽子へ形をつなぎ、最後はお茶会の一枚へ。',
uploads:['references/'+modelFiles[1],'references/'+modelFiles[2],'references/'+modelFiles[3],'backgrounds/background-02-garden.png','storyboards/storyboard-02.png'],board:5,
environments:[{id:10,pic:4,en:'the sunny manor rose garden, with a white tea table, cream terrace steps and soft peach-green light',ja:'日向の館のバラ庭園。白い茶卓、クリーム色の段差、桃色と緑の柔らかな光'}],
summaryEN:'Present <Subject 7>, <Subject 6>, <Subject 5>, <Subject 3> and <Subject 4> through affectionate everyday gestures around <Subject 10>. The sequence follows personality and visual match cuts, ending on their relaxed tea gathering. Use <Picture 5> for the six compositions. Bright close-ups and playful reactions create a cute character-introduction passage.',
summaryJA:'<Subject 10> の周りで、<Subject 7>、<Subject 6>、<Subject 5>、<Subject 3>、<Subject 4> の日常の仕草を親しみやすく見せる。性格と画面内の形をつなぐ編集で進み、和やかなお茶会へ着地する。6つの構図は <Picture 5>。明るい寄りと小さな反応で、かわいいキャラクター紹介を作る。',
shotsEN:[
'Open on the rim of a silver tray held by <Subject 7> in <Subject 10>. Tilt quickly from the cup to her blue eyes and green neck bow as she finishes setting the tray at the edge of frame. She meets the camera with an assured, gentle smile. Her small silver braids remain distinct from the maid headband. A single porcelain contact and soft apron rustle mark the movement; garden air stays light.',
'Match the tray’s bright rim to the edge of the purple book held by <Subject 6>. In a tight bust shot beneath a flowering arch, she lowers the book just enough to reveal a shy smile; long purple hair and the crescent cap frame her face. Slide a little to the right, letting blurred rose petals cross the far background. One page flutters and settles, creating a small dry sound.',
'Cut to <Subject 5> framed from the waist up beside a sunlit hedge, green star beret and twin red braids clearly visible. A petal rests on her cap. She notices our gaze, gives a slightly embarrassed smile and a quick friendly salute. The camera makes a short upward bounce and settles at eye level. Her tunic remains green and gold; loose white trousers briefly appear at the lower edge. Cloth and a leaf rustle accompany her.',
'Cut to <Subject 3> holding a small steamed bun in both hands beneath her chin. She tilts her blonde bob toward the lens with a delighted closed-mouth expression; her red side ribbon and white collar stand out against a soft peach garden background. Push in a little as she offers the bun forward, keeping her hands and face anatomically clear. A paper wrapper gives one delicate crinkle.',
'Cut to <Subject 4> proudly lifting a tiny ice flower between thumb and forefinger. A chest-up camera arc catches blue hair, red neck ribbon and the six translucent wing shards behind her. She gives an exaggerated confident wink while the flower briefly glitters in sunlight. Keep its scale small and charming. A crisp ice tick and a light sleeve swish punctuate the pose, followed by ordinary garden wind.',
'Cut wider to the five together around the white tea table: <Subject 7> stands at the right with the tray, <Subject 6> sits centrally with her book, <Subject 5> leans near the left chair, while <Subject 3> and <Subject 4> share the foreground. They exchange small smiles and glance toward us. Pull back gently enough to retain readable faces and the bright rose-garden atmosphere. End on this friendly ensemble at 00:10.000, with porcelain, pages and leaves.'
],
shotsJA:[
'<Subject 10> で <Subject 7> が持つ銀のトレイの縁から始める。カップから青い瞳と緑の胸リボンへ素早くティルトし、トレイを画面の端に置き終えた姿を見せる。こちらを見て、落ち着いた柔らかな笑み。銀髪の小さな編み込みとメイドの髪飾りを描き分ける。磁器が一度触れる音とエプロンの擦れる音、軽い庭の空気。',
'トレイの明るい縁から <Subject 6> の紫の本の縁へ形を合わせて切る。花のアーチの下で胸上に寄り、本を少し下げて内気な笑みを見せる。長い紫髪と三日月の帽子で顔を囲む。少し右へ移動し、奥にぼけたバラの花びらを流す。ページが一枚揺れて落ち着く乾いた小さな音。',
'日向の生垣の横の <Subject 5> を腰上で捉える。星付き緑帽と二本の赤い編み込み。帽子に花びらが一枚載っている。こちらの目線に気づき、少し照れた笑みから親しみのある短い敬礼へ。カメラは小さく上へ弾んで目の高さに止まる。緑と金の長衣、画面下には白いズボンを一瞬見せる。布と葉の音。',
'小さな蒸し饅頭を両手で顎の下に持つ <Subject 3> へ切る。金髪ボブをレンズへ傾け、口を閉じた嬉しそうな顔。桃色にぼけた庭を背に、赤い横リボンと白襟を見せる。饅頭を少しこちらへ差し出す動きに合わせて寄り、手と顔を明瞭に保つ。包み紙が一度だけ小さく鳴る。',
'<Subject 4> が指先に小さな氷の花を誇らしく掲げる寄りへ切る。胸上を回り込む短いカメラで青髪、赤い胸リボン、背後の6本の氷の翼を捉える。花が日光にきらめき、大げさに自信満々のウインクをする。氷の花は小さくかわいらしい大きさ。氷の澄んだ短い音と袖の音、続いて普通の庭の風。',
'白い茶卓を囲む5人へ引く。右にトレイを持つ <Subject 7>、中央に本を持って座る <Subject 6>、左の椅子のそばに寄る <Subject 5>。手前に <Subject 3> と <Subject 4>。小さな笑顔を交わしてこちらを見る。顔を読める大きさに残し、明るい庭の空気を保って穏やかに引く。磁器、本、葉の音と共に、親しみのある集合構図で00:10.000に終了。'
]},
{id:'clip-03',title:'いたずらに、笑顔がこぼれる',cast:[8,9,1,2],sources:{1:[1,'top','上段'],2:[1,'bottom','下段'],8:[2,'top','上段'],9:[2,'bottom','下段']},times:[0,1.5,3,4.5,6,7.5],labels:['日傘から瞳へピント送り','フランがカメラへ覗き込む','霊夢が帽子の花びらを取る','フランと魔理沙の帽子いたずら','バラ越しに四人のじゃれ合い','姉妹の笑顔へゆっくり寄る'],pacing:'日向の庭園で4人がじゃれ合う。花びらや指先から瞳へのピント送り、短い回り込み、手前のバラを横切る横移動で奥行きと楽しさを出す。最後は姉妹の笑顔に寄って落ち着く。',
uploads:['references/'+modelFiles[0],'references/'+modelFiles[4],'backgrounds/background-02-garden.png','storyboards/storyboard-03.png'],board:4,
environments:[{id:10,pic:3,en:'the warm manor garden terrace with rose petals, pale stone and layered foreground flowers',ja:'バラの花びら、淡い石の段差、手前の花々がある暖かな館の庭園'}],
summaryEN:'Show <Subject 8>, <Subject 9>, <Subject 1> and <Subject 2> sharing gentle, mischievous play in <Subject 10>. Use <Picture 4> for the six compositions. A petal taken from a cap, a teasing hat-brim nudge and one playful sidestep create an affectionate character passage. Motivate focus changes with each gesture and its smiling reaction; use short arcs, gentle pullbacks and lateral flower parallax. Finish on the sisters leaning together.',
summaryJA:'<Subject 10> で <Subject 8>、<Subject 9>、<Subject 1>、<Subject 2> が親しげにじゃれ合う。6つの構図は <Picture 4>。帽子の花びらを取る、帽子のつばをちょんと押す、笑顔で一歩かわす仕草で仲のよさを見せる。仕草と相手の表情に合わせてピントを送り、短い回り込み、緩い引き、手前の花の視差を使う。最後は肩を寄せる姉妹へ。',
shotsEN:[
'Begin close to the rose-colored parasol rim in <Subject 10>, its fabric briefly sharp. It sweeps aside to reveal <Subject 8>, blue bob and pink cap glowing in warm light. Smoothly transfer focus from the near rim to her red eyes as she tilts her chin with a confident little smile. Arc a few degrees at eye level and settle on her face. A purple bat-wing edge frames her shoulder; parasol cloth and a tiny handle click accent the reveal.',
'Cut closer as <Subject 9> peeks around her sister’s shoulder toward the lens. Her side ponytail bounces once, white cap and red bow clearly separate from Remilia’s pink cap. Ease backward twenty centimeters as she comes nearer, transferring focus from her sister to Flandre’s mischievous eyes. Keep the near cheek crisp and the rose garden softly blurred. Rainbow crystals remain behind her shoulders. A sleeve swish and two small crystal clicks accompany the playful intrusion.',
'Cut to <Subject 1> at left and <Subject 8> at right in an intimate garden two-shot. Reimu gently lifts one rose petal from Remilia’s cap and shows it between her fingertips. Start focused on the petal, then shift to Remilia’s eyes as she leans back slightly with an amused, mock-surprised blink. Reimu smiles at her reaction. Make a small sideways arc, preserving both faces and separate hands. A delicate fabric brush and leaves provide the accent.',
'Cut to <Subject 2> at left and <Subject 9> at right. Flandre lightly nudges the outer hat brim with her right index finger; Marisa lifts its front edge with her own right hand and reveals an amused grin. Their other hands rest low. Slide gently sideways, first focusing on the fingertip and brim, then on Marisa’s eyes as they appear. Keep wrists connected naturally to their own arms. A soft hat-fabric tap punctuates this friendly tease.',
'Widen to a waist-up group: Marisa foreground left, Flandre foreground right, Reimu rear left and Remilia rear right. Marisa takes one playful sidestep as Flandre reaches toward the hat, smiling over her shoulder. Reimu and Remilia exchange delighted looks. Track sideways behind a nearby rose cluster, letting its soft blur briefly skim the frame edge before revealing all four. Settle with every face readable at moderate depth of field. One light footstep, leaves and cloth carry the motion.',
'Cut to <Subject 8> and <Subject 9> shoulder to shoulder. Flandre leans affectionately toward Remilia, whose poised expression melts into a smile. Begin on a nearby crystal glint, then transfer focus to both faces on the same plane while slowly pushing in. Their distinct wings frame the warm garden bokeh. Settle the camera as both look toward us; hold the shared smile through 00:10.000. A soft crystal tick and garden breeze finish the moment.'
],
shotsJA:[
'<Subject 10> で、バラ色の日傘の縁を近くから捉え、最初だけ布にピントを置く。縁が横へ抜け、水色ボブと桃色帽に暖かな光を受けた <Subject 8> が現れる。手前の傘から赤い瞳へ滑らかにピントを送り、顎を少し傾けた自信のある笑みを見せる。目の高さで数度だけ回り込み、顔で止める。肩の紫の翼、傘の布、柄の小さな音。',
'姉の肩越しに <Subject 9> がレンズを覗く寄りへ切る。横ポニーテールが一度弾み、白帽と赤リボンをレミリアの桃色帽から描き分ける。近づく動きに合わせて20センチほど緩く引き、姉からフランのいたずらっぽい瞳へピントを送る。近い頬を明瞭に保ち、庭のバラは柔らかくぼかす。虹色の結晶は肩の後ろ。袖の音と結晶が二度触れる小さな音。',
'庭園の親密な二人のカットへ。左に <Subject 1>、右に <Subject 8>。霊夢がレミリアの帽子から花びらを一枚そっと取り、指先で見せる。最初は花びらにピントを置き、レミリアが少し身を引いておどけた驚きのまばたきをする瞳へ送る。霊夢はその反応に笑顔を返す。横へ小さく回り込み、両方の顔と手を描き分ける。かすかな布の擦れと葉の音。',
'左の <Subject 2> と右の <Subject 9> へ切る。フランが本人の右手人差し指で帽子のつばの外側を軽く押し、魔理沙は本人の右手で前の縁を持ち上げ、楽しげな笑みを見せる。それぞれ反対の手は低い位置。ゆっくり横移動し、指先とつばから、現れた魔理沙の瞳へピントを移す。手首はそれぞれの腕へ自然につなげる。帽子の布の小さな音で、親しげないたずらを刻む。',
'腰上の4人へ引く。手前左に魔理沙、手前右にフラン、奥左に霊夢、奥右にレミリア。フランが帽子へ手を伸ばし、魔理沙は一歩だけ横へかわしながら肩越しに笑う。霊夢とレミリアが楽しそうに目を合わせる。近くのバラの陰を横移動し、柔らかな前ぼけが画面の縁を短くかすめた後、4人を見せる。中程度の被写界深度で全員の顔が読める位置へ止める。一度の軽い足音、葉、衣擦れ。',
'肩を並べる <Subject 8> と <Subject 9> へ切る。フランが親しげに寄り、レミリアの澄ました表情が笑みにほどける。手前の結晶のきらめきから、同じ距離にある二人の顔へピントを送り、ゆっくり寄る。異なる翼が暖かな庭のぼけを縁取る。二人がこちらを見るところでカメラを落ち着かせ、00:10.000まで笑顔を保つ。小さな結晶音と庭の風で締める。'
]},
{id:'clip-04',title:'ひとりずつ、そしてみんなで',cast:[3,7,4,6,5,9,8,2,1],sources:{1:[1,'top','上段'],2:[1,'bottom','下段'],3:[2,'top','上段'],4:[2,'bottom','下段'],5:[3,'single character','唯一の人物'],6:[4,'top','上段'],7:[4,'bottom','下段'],8:[5,'top','上段'],9:[5,'bottom','下段']},times:[0,.75,1.5,2.25,3,3.75,4.5,5.25,6,6.75],labels:['ルーミア','咲夜','チルノ','パチュリー','美鈴','フランドール','レミリア','魔理沙','霊夢','9人の集合絵'],pacing:'9人を一人0.75秒の顔アップで切り替える。6.75秒から9人集合へ。最後の3.25秒は同じ集合構図で締める。',
uploads:[...modelFiles.map(f=>'references/'+f),'storyboards/storyboard-04-portraits.png','references/final-ensemble.png'],board:6,
environments:[{id:10,pic:7,en:'the sunlit rose-garden setting and two-row cast arrangement of the final ensemble illustration',ja:'最終集合絵の日向のバラ庭園と、前後二列の人物配置'}],
summaryEN:'Give all nine characters separate direct-to-camera close-ups in this exact order: <Subject 3>, <Subject 7>, <Subject 4>, <Subject 6>, <Subject 5>, <Subject 9>, <Subject 8>, <Subject 2>, <Subject 1>. Each portrait lasts 0.750 seconds and uses the corresponding panel of <Picture 6>. At 00:06.750 cut to the complete nine-person ensemble in <Subject 10>, converging on <Picture 7> through the end at 00:10.000. This group image is the final shot of the opening.',
summaryJA:'9人を一人ずつカメラ目線の顔アップで、<Subject 3>、<Subject 7>、<Subject 4>、<Subject 6>、<Subject 5>、<Subject 9>、<Subject 8>、<Subject 2>、<Subject 1> の順に見せる。各0.750秒で <Picture 6> の対応するコマを参照。00:06.750に <Subject 10> の9人集合へ切り、<Picture 7> の構図に到達して00:10.000まで保つ。この集合絵がOPの最終ショット。',
shotsEN:[
'Open on <Subject 3> in a tight face close-up matching the first panel of <Picture 6>. Blonde bob and red side ribbon frame her delighted smile. She tilts her head once toward the viewer against peach bokeh. A tiny cloth swish punctuates the motion.',
'Cut directly to <Subject 7>, silver braids and maid headband fully readable. Keep approximately the same eye line and face size. She gives a composed small smile with one blink against pale mint. A soft apron rustle accompanies a slight forward camera nudge.',
'Cut to <Subject 4> against icy blue, her blue hair bow inside frame. She finishes one confident wink, chin tipped upward. The camera is steady so her expression reads immediately. A short ice tick supplies the accent.',
'Cut to <Subject 6> against lavender. Her crescent cap frames her eyes; the purple book stays below her chin as she offers a shy smile. Make a tiny lateral camera move. One page edge flutters with a dry papery sound.',
'Cut to <Subject 5> against fresh green. Her red twin braids and star beret identify her immediately. With fingertips already at the brim, she gives a warm smile toward the lens. A quick cloth brush accompanies her small salute.',
'Cut to <Subject 9> against peach-pink. Her blonde side ponytail and red cap bow bounce slightly; a rainbow crystal glints at the far edge. She gives a sweet mischievous grin. Add one irregular crystal click and a minimal forward push.',
'Cut to <Subject 8> against rose, with her light-blue bob, pink cap and purple wing edge distinct. She turns her eyes directly toward us and smiles with playful composure. Keep the head movement small; the sleeve produces a gentle swish.',
'Cut to <Subject 2> against warm gold. Frame the white hat bow and blonde braid around her face. She tips the brim just enough to reveal a cheeky wink, already facing the camera. A short fabric snap lands on the gesture.',
'Cut to <Subject 1> against soft coral. Her red-white bow and chestnut bangs frame a clear, warm smile. Push forward slightly as she meets our eyes; her paper talisman remains below her face. A single paper flick prepares the ensemble cut.',
'Cut to all nine already arranged together in <Subject 10>, following <Picture 7>. Front row left-to-right: Cirno, Reimu, Marisa, Flandre; rear row: Rumia, Meiling, Patchouli, Sakuya, Remilia. Every face is visible. Pull back gently until 00:08.500, then hold the full composition with subtle hair, petals and smiling eyes through 00:10.000. End here on the welcoming group illustration, accompanied by soft garden wind and one quiet fabric flutter.'
],
shotsJA:[
'<Picture 6> の最初のコマに合わせ、<Subject 3> の顔アップから始める。金髪ボブと赤い横リボンで嬉しそうな笑みを囲む。桃色のぼけを背に、こちらへ一度だけ首を傾ける。小さな布の音。',
'<Subject 7> へ直接切る。銀髪の編み込みと髪飾りを明瞭にし、目の高さと顔の大きさを前と揃える。淡いミント色を背に、落ち着いた小さな笑みと一度のまばたき。少し前へ寄り、エプロンの音。',
'氷の青を背に <Subject 4> へ切る。青い髪リボンを画面に収め、顎を上げて自信のあるウインクを一つ。表情が即座に読めるようカメラを固定する。氷の短い音。',
'薄紫を背に <Subject 6> へ切る。三日月の帽子で目元を囲み、紫の本を顎より下へ保って内気な笑み。カメラをほんの少し横へ動かす。ページの端が揺れる乾いた紙の音。',
'若草色を背に <Subject 5> へ切る。二本の赤い編み込みと星付き帽子で一目で分かるようにする。すでに指先をつばに添えた姿から、レンズへ暖かな笑み。小さな敬礼と布の音。',
'桃色を背に <Subject 9> へ切る。金髪の横ポニーテールと帽子の赤リボンが小さく弾み、画面の端で虹色の結晶が光る。甘くいたずらっぽい笑み。結晶が一度不規則に鳴り、カメラはわずかに寄る。',
'バラ色を背に <Subject 8> へ切る。水色ボブ、桃色帽、紫の翼の縁を描き分ける。こちらへ目を向け、余裕のあるかわいい笑み。頭の動きは小さくし、袖の音を柔らかく添える。',
'暖かな金色を背に <Subject 2> へ切る。白い帽子リボンと金髪の編み込みで顔を囲む。すでにカメラへ向いた姿から、つばを少し上げ、いたずらっぽいウインクを見せる。短い布の音。',
'淡い珊瑚色を背に <Subject 1> へ切る。赤白リボンと栗色の前髪で明るい暖かな笑みを囲む。目が合う瞬間に少しだけ寄り、札は顔より下に置く。札の短い一音で集合への切り替えを準備する。',
'<Subject 10> に9人がすでに揃った構図へ切り、<Picture 7> に合わせる。前列は左からチルノ、霊夢、魔理沙、フラン。後列はルーミア、美鈴、パチュリー、咲夜、レミリア。全員の顔を見せる。00:08.500まで穏やかに引き、髪・花びら・笑う目の小さな動きだけ残して00:10.000まで集合構図を保つ。柔らかな庭の風と小さな布の音。この親しみのある集合絵で完了する。'
]}
];
const appearances=[{1:[1,3,4,6],2:[2,3,5,6],10:[1,2,3,6],11:[4,5]},{7:[1,6],6:[2,6],5:[3,6],3:[4,6],4:[5,6],10:[1,2,3,4,5,6]},{8:[1,2,3,5,6],9:[2,4,5,6],1:[3,5],2:[4,5],10:[1,2,3,4,5,6]},Object.fromEntries([...clips[3].cast.map((id,i)=>[id,[i+1,10]]),[10,[10]]])];
const sectionNames=['subject_definitions','summary','retention_analysis','detailed_description','overall_soundscape','non_diegetic_music'];
for(const [index,c]of clips.entries()){
 for(const lang of ['en','ja']){
  const en=lang==='en';
  const defs=c.cast.map(id=>{const x=cast[id],s=c.sources[id];const appearanceEN=index===2&&id===2?x.en.replace(', brown broom and octagonal focus',''):x.en;const appearanceJA=index===2&&id===2?x.jp.replace('、茶色の箒、八角形の魔法の道具',''):x.jp;return en?`<Subject ${id}> is ${x.name}, the ${s[1]} character in <Picture ${s[0]}>: ${appearanceEN}.`:`<Subject ${id}> は <Picture ${s[0]}> の${s[2]}の${x.ja}。${appearanceJA}。`;});
  for(const e of c.environments)defs.push(en?`<Subject ${e.id}> is ${e.en}, from <Picture ${e.pic}>.`:`<Subject ${e.id}> は <Picture ${e.pic}> の${e.ja}。`);
  defs.push(en?`<Picture ${c.board}> is the clean visual board, read left-to-right and top-to-bottom, mapping ${index===3?'the first nine portrait shots':'[Shot 1] through [Shot 6]'}. It provides composition and identity cues; the written timeline supplies motion and cuts.`:`<Picture ${c.board}> は左から右、上段から下段へ読むクリーンな画像。${index===3?'最初の9つの顔アップ':'[Shot 1]〜[Shot 6]'}の構図と人物を参照し、動きとカット時刻は文章に従う。`);
  if(index===3)defs.push(en?'<Picture 7> is the final ensemble composition anchor for [Shot 10], with all nine cast members together.':'<Picture 7> は [Shot 10] の最終集合構図。全9人が一緒に写る。');
  const summary=(index===3?'[reference generation + keyframe completion] ':'[reference generation] ')+(en?'Create exactly 10.000 seconds, 16:9. ':'16:9、正確に10.000秒。')+(en?c.summaryEN:c.summaryJA)+(en?' Use bright polished 2D anime, expressive eyes and a cute, upbeat visual-novel opening mood. Each shot fills one frame as a complete scene; costumes and faces follow the model sheets.':' 明るい2Dアニメ、大きく表情豊かな瞳、ポップでかわいいギャルゲームOPの空気。各カットを一つの情景として画面いっぱいに描き、衣装と顔は設定画を保つ。');
  const scope=id=>appearances[index][id].map(i=>'[Shot '+i+']').join(', ');
  const ret=c.cast.map(id=>en?`<Subject ${id}> (appears in ${scope(id)}): fully_preserved - retain ${cast[id].name}'s face, hair, headwear and costume across expressions and camera angles.`:`<Subject ${id}>（${scope(id)}）：fully_preserved - ${cast[id].ja}の顔、髪、髪飾り、衣装を表情や画角が変わっても保つ。`);
  if(index===0){const shots='[Shot 2], [Shot 5]';ret.push(en?`<Subject 2> (${shots}, body-relative handedness and broom): fully_preserved - her anatomical right hand stays on the shaft; her anatomical left hand handles the hat or focus as specified. In a frontal view, her right arm originates at screen-left and her left arm at screen-right. Each hand remains connected to its own shoulder through camera motion and cuts. Her right thumb opposes four curled fingers around the shaft. One continuous broom shaft leads with its bare wooden end; the tied straw bundle trails behind her hips.`:`<Subject 2>（${shots}、本人基準の左右と箒）：fully_preserved - 本人の右手が柄を握り続け、本人の左手が指定に応じて帽子または道具を扱う。正面では本人の右肩が画面左、左肩が画面右に位置する。カメラ移動とカットを通じ、各手は同じ側の肩につながる。右手の親指と巻き付けた4本の指を柄の両側へ配置。箒は一本の連続した柄で、木の先端が進行方向、束ねた穂が腰の後ろに続く。`);}
  if(index===2)ret.push(en?'<Subject 2> and <Subject 9> ([Shot 4] hat interaction): fully_preserved - Marisa lifts the front brim with her anatomical right hand; Flandre nudges the outer brim with her own right index finger. Their other hands stay low, each wrist continuous with its own forearm. Keep their faces recognizable through the focus shift.':'<Subject 2> と <Subject 9>（[Shot 4] 帽子のやり取り）：fully_preserved - 魔理沙は本人の右手で帽子の前の縁を持ち上げ、フランは本人の右手人差し指で外側を軽く押す。二人の反対の手は低く保ち、各手首を自分の前腕へつなげる。ピント送りの間も人物を識別できる顔を保つ。');
  for(const e of c.environments)ret.push(en?`<Subject ${e.id}> (appears in ${scope(e.id)}): fully_preserved - keep the bright location design while changing framing.`:`<Subject ${e.id}>（${scope(e.id)}）：fully_preserved - 明るい環境の特徴を保ち、画角を変える。`);
  ret.push(en?`<Picture ${c.board}> (shot composition): partially_preserved - preserve panel order and character placement; follow the written camera movement and exact timing.`:`<Picture ${c.board}>（構図参照）：partially_preserved - コマ順と人物配置を保ち、カメラの動きと正確な時刻は文章を優先。`);
  if(index===3)ret.push(en?'<Picture 7> ([Shot 10] final frame): fully_preserved - retain the complete cast, two-row arrangement and friendly expressions.':'<Picture 7>（[Shot 10] 最終フレーム）：fully_preserved - 全員、前後二列の配置、親しみのある表情を保つ。');
  const body=(en?'Crisp cel animation, warm high-key light, expressive character acting, clean silhouettes and bright pastel accents.\n':'明瞭なセルアニメ、暖かく明るい光、表情の演技、読みやすい輪郭、パステル色のアクセント。\n')+(en?c.shotsEN:c.shotsJA).map((s,i)=>`[Shot ${i+1}] ${i?'At 00:'+c.times[i].toFixed(3).padStart(6,'0')+', ':''}${s}`).join('\n');
  const sound=index===2?(en?'Quiet garden air, leaves, soft sleeves, parasol and hat fabric, one light footstep and tiny physical crystal clicks. Match each accent to the visible gesture and leave gentle gaps. Smiles and playful reactions are silent. No dialogue, narration, laughter, shouts, vocals or music.':'静かな庭の風、葉、柔らかな袖、日傘と帽子の布、一度の軽い足音、小さな結晶同士の接触音。見える仕草に合わせ、穏やかな余白を残す。笑顔やじゃれ合いの反応は声を出さず表情で示す。台詞、ナレーション、笑い声、掛け声、歌声、音楽はなし。'):(en?'Only sounds tied to the visible setting and gestures: wind, leaves, cloth, paper, porcelain and brief nonmelodic magical transients where specified. Use quiet gaps between close-up accents. No dialogue, narration, laughter, shouts, vocals or music.':'見えている環境と仕草の効果音のみ。風、葉、布、紙、磁器、指定箇所の短く非旋律的な魔法音。寄りのアクセントの間は静かな余白にする。台詞、ナレーション、笑い声、掛け声、歌声、音楽はなし。');
  const music=en?'None. No BGM, score, song or musical accompaniment.':'なし。BGM、劇伴、歌、音楽の伴奏は入れない。';
  const values=[defs.join('\n'),summary,ret.join('\n'),body,sound,music];
  fs.writeFileSync(path.join(base,'prompts',c.id+'.'+lang+'.txt'),sectionNames.map((n,i)=>n+':\n'+values[i]).join('\n\n')+'\n');
 }
}
const plan={title:'SCARLET PILGRIMAGE',concept:'Pop character-introduction opening',revision:3,duration_seconds:40,aspect_ratio:'16:9',music:false,dialogue:false,finale_order:clips[3].cast.map(i=>cast[i].name),finale_group_start_seconds:36.75,finale_group_end_seconds:40,cast,clips:clips.map((c,i)=>({id:c.id,title:c.title,global_start_seconds:i*10,duration_seconds:10,cast:c.cast.map(id=>cast[id].name),shot_starts_seconds:c.times,shot_labels_ja:c.labels,pacing_ja:c.pacing,upload_order:c.uploads,english_prompt:c.id+'.en.txt',japanese_prompt:c.id+'.ja.txt'}))};
fs.writeFileSync(path.join(base,'prompts/shot-plan.json'),JSON.stringify(plan,null,2)+'\n');
console.log('Wrote eight prompts and a new 40-second, 28-cut character-led plan.');
