const crypto = require('node:crypto');
function makePlaytestHtml(rom, wasm, title, player, notices) {
 if (rom.length < 32768 || rom.length % 16384 || rom.length > 8*1024*1024) throw Error('Invalid ROM size');
 const sha=crypto.createHash('sha256').update(rom).digest('hex');
 const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const values={ROM_BYTES:rom.toString('base64'),WASM_BYTES:wasm.toString('base64'),ROM_HASH:sha,ROM_FILENAME:title};
 const script=(Object.entries(values).map(([k,v])=>'const '+k+'='+JSON.stringify(v)+';').join('')+player).replace(/<\/script/gi,'<\\/script');
 const html=`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><style>body{font-family:system-ui,sans-serif;background:#091629;color:#eef5ff;max-width:760px;margin:24px auto;padding:0 16px}canvas{width:min(100%,480px);height:auto;image-rendering:pixelated;background:#000;display:block;margin:16px 0}button,select{font:inherit;padding:10px;min-height:44px}button{touch-action:none}nav,.pad{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}small{overflow-wrap:anywhere}input{max-width:100%}summary{cursor:pointer}pre{white-space:pre-wrap;font-size:11px}</style><h1>${escape(title)}</h1><p>実ROM試遊 / 矢印移動・Z=A・X=B・Enter=START・Shift=SELECT</p><nav><label>機種 <select id="mode"><option value="cgb">GBC</option><option value="dmg">GB</option></select></label><button id="pause">一時停止</button><button id="sound">音声ON</button><button id="reset">再起動</button></nav><canvas id="screen" width="160" height="144" aria-label="ゲーム画面"></canvas><div class="pad">${['Left','Up','Down','Right','A','B','Start','Select'].map((k,i)=>`<button data-key="${k}" aria-label="${k}">${['←','↑','↓','→','A','B','START','SELECT'][i]}</button>`).join('')}</div><p id="status" role="status">準備中</p><nav><button id="rom">ROMダウンロード</button><button id="save">セーブ書出し</button><label>セーブ読込 <input id="load" type="file" accept=".sav"></label></nav><small>ROM SHA-256: ${sha}</small><p>処理が重いときは進行を遅くします。保存はこのROM版ごとです。次の版へはセーブを書き出して引き継いでください。</p><details><summary>エミュレーターのライセンス</summary><p>Boytacean ${'0.13.2'} / João Magalhães / https://github.com/joamag/boytacean</p><pre>${escape(notices)}</pre></details><script>${script}</script></html>`;
 return html;
}
module.exports={makePlaytestHtml};
